# Generated by Django 5.0.2 on 2024-03-30 06:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('userprofileimage', models.ImageField(upload_to='profile')),
                ('dob', models.DateField(blank=True, null=True)),
                ('department', models.CharField(choices=[('CSE', 'Computer Science & Engineering'), ('EEE', 'Electrial & Electronics Engineering'), ('CE', 'Civil  Engineering'), ('DS', 'Data Science and Analytics'), ('AD', 'Admin')], max_length=4)),
                ('usertype', models.CharField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor')], max_length=7)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='patient_appointments', serialize=False, to='Users.person')),
                ('appointment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=False)),
                ('slot', models.CharField(choices=[('slot1', '9AM -11AM'), ('slot2', '11AM-1PM'), ('slot3', '1PM-5PM')], max_length=5)),
                ('problem', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
