# Generated by Django 5.0.2 on 2024-03-29 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_appointment_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_appointment',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
    ]
