# Generated by Django 5.0.2 on 2024-03-29 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_remove_appointment_unique_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='problem',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
