# Generated by Django 5.0.2 on 2024-04-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='diagnosis',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='prescription',
            name='symptoms',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
