# Generated by Django 5.0.2 on 2024-05-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_remove_test_prescription_id_prescription_drug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='diagnosis',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='drug',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='symptoms',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='test',
            field=models.TextField(default='None'),
        ),
    ]
